//! FFI bindings to the flexe C library
//!
//! This module provides safe Rust wrappers around the flexe session API.
//! The raw bindings are generated by bindgen in build.rs.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

use std::ffi::CString;
use std::ptr;
use std::sync::Arc;
use std::os::raw::{c_int, c_void};
use parking_lot::Mutex;
use anyhow::{Result, bail};

use crate::input::TouchState;

// pthread_mutex_t FFI declarations (Windows)
#[cfg(target_os = "windows")]
#[repr(C)]
struct pthread_mutex_t {
    _opaque: [u8; 64], // Opaque type for pthread mutex on Windows
}

#[cfg(target_os = "windows")]
extern "C" {
    fn pthread_mutex_init(mutex: *mut pthread_mutex_t, attr: *const std::ffi::c_void) -> i32;
    fn pthread_mutex_destroy(mutex: *mut pthread_mutex_t) -> i32;
}

#[cfg(not(target_os = "windows"))]
type pthread_mutex_t = std::ffi::c_void;

// Include pre-generated bindings (no bindgen required)
#[path = "flexe_bindings.rs"]
mod bindings;
use bindings::*;

/// Configuration for creating a flexe session
#[derive(Debug, Clone)]
pub struct SessionConfig {
    /// Path to the firmware .bin file (required)
    pub bin_path: String,
    /// Path to the ELF symbol file (optional)
    pub elf_path: Option<String>,
    /// Path to SD card image file (optional)
    pub sdcard_path: Option<String>,
    /// SD card size in bytes (0 = auto-detect)
    pub sdcard_size: u64,
    /// Override entry point (0 = use from .bin)
    pub entry_override: u32,
    /// Override initial stack pointer (0 = default 0x3FFE0000)
    pub initial_sp: u32,
    /// Single-core mode (disable Core 1)
    pub single_core: bool,
    /// Enable window spill/fill tracing
    pub window_trace: bool,
    /// Enable spill/fill verification
    pub spill_verify: bool,
    /// Native FreeRTOS mode (let firmware run real scheduler)
    pub native_freertos: bool,
}

impl Default for SessionConfig {
    fn default() -> Self {
        Self {
            bin_path: String::new(),
            elf_path: None,
            sdcard_path: None,
            sdcard_size: 0,
            entry_override: 0,
            initial_sp: 0,
            single_core: false,
            window_trace: false,
            spill_verify: false,
            native_freertos: false,
        }
    }
}

/// Safe wrapper around flexe_session_t
pub struct FlexeSession {
    session: *mut flexe_session_t,
    _bin_path: CString,
    _elf_path: Option<CString>,
    _sdcard_path: Option<CString>,
    // Keep framebuffer alive for the session lifetime
    _framebuffer: Arc<Mutex<Vec<u16>>>,
    #[cfg(target_os = "windows")]
    _framebuf_mutex: Option<Box<pthread_mutex_t>>, // Keep pthread mutex alive
    // Keep touch state Arc alive for the session lifetime
    _touch_state: Option<Arc<Mutex<TouchState>>>,
}

unsafe impl Send for FlexeSession {}
unsafe impl Sync for FlexeSession {}

/// C-compatible touch callback function
///
/// This function is called by the flexe emulator to query touch state.
/// The ctx parameter is a pointer to Arc<Mutex<TouchState>>.
extern "C" fn touch_callback(x: *mut c_int, y: *mut c_int, ctx: *mut c_void) -> c_int {
    if ctx.is_null() || x.is_null() || y.is_null() {
        return 0;
    }

    unsafe {
        // Cast ctx back to Arc<Mutex<TouchState>>
        let touch_state = &*(ctx as *const Arc<Mutex<TouchState>>);
        let state = touch_state.lock();

        // Write coordinates to the output pointers
        *x = state.x;
        *y = state.y;

        // Return 1 if touch is down, 0 if up
        if state.down { 1 } else { 0 }
    }
}

impl FlexeSession {
    /// Create a new flexe session with the given configuration
    pub fn new(
        config: SessionConfig,
        framebuffer: Arc<Mutex<Vec<u16>>>,
        _framebuf_mutex: Arc<Mutex<()>>,
        touch_state: Option<Arc<Mutex<TouchState>>>,
    ) -> Result<Self> {
        if config.bin_path.is_empty() {
            bail!("bin_path is required");
        }

        let bin_path = CString::new(config.bin_path.clone())?;
        let elf_path = config.elf_path.as_ref()
            .map(|s| CString::new(s.clone()))
            .transpose()?;
        let sdcard_path = config.sdcard_path.as_ref()
            .map(|s| CString::new(s.clone()))
            .transpose()?;

        unsafe {
            let mut cfg: flexe_session_config_t = std::mem::zeroed();

            cfg.bin_path = bin_path.as_ptr();
            cfg.elf_path = elf_path.as_ref()
                .map(|s| s.as_ptr())
                .unwrap_or(ptr::null());
            cfg.sdcard_path = sdcard_path.as_ref()
                .map(|s| s.as_ptr())
                .unwrap_or(ptr::null());
            cfg.sdcard_size = config.sdcard_size;
            cfg.entry_override = config.entry_override;
            cfg.initial_sp = config.initial_sp;
            cfg.single_core = if config.single_core { 1 } else { 0 };
            cfg.window_trace = if config.window_trace { 1 } else { 0 };
            cfg.spill_verify = if config.spill_verify { 1 } else { 0 };
            cfg.native_freertos = if config.native_freertos { 1 } else { 0 };

            // Set up framebuffer
            // Get pointer to the framebuffer data
            // This is safe because:
            // 1. The Vec was pre-allocated with exact size (no reallocation)
            // 2. We keep the Arc<Mutex<Vec>> alive in _framebuffer field
            // 3. The Vec won't be dropped until FlexeSession is dropped
            let fb_ptr = {
                let fb = framebuffer.lock();
                fb.as_ptr() as *mut u16
            };

            cfg.framebuf = fb_ptr;
            cfg.framebuf_w = 320;
            cfg.framebuf_h = 240;

            // Create pthread mutex for framebuffer synchronization
            #[cfg(target_os = "windows")]
            let framebuf_mutex_box = {
                let mut mutex: Box<pthread_mutex_t> = Box::new(std::mem::zeroed());
                pthread_mutex_init(mutex.as_mut(), ptr::null());
                Some(mutex)
            };

            #[cfg(target_os = "windows")]
            {
                cfg.framebuf_mutex = framebuf_mutex_box.as_ref().unwrap().as_ref() as *const _ as *mut _;
            }

            #[cfg(not(target_os = "windows"))]
            {
                cfg.framebuf_mutex = ptr::null_mut();
            }

            // Set up callbacks
            cfg.uart_cb = None;
            cfg.uart_ctx = ptr::null_mut();

            // Register touch callback if touch_state is provided
            if let Some(ref ts) = touch_state {
                cfg.touch_fn = Some(touch_callback);
                // Convert Arc to raw pointer for ctx
                // We keep the Arc alive by storing it in the struct
                let ctx_ptr = Arc::as_ptr(ts) as *mut c_void;
                cfg.touch_ctx = ctx_ptr;
            } else {
                cfg.touch_fn = None;
                cfg.touch_ctx = ptr::null_mut();
            }

            let session = flexe_session_create(&cfg);
            if session.is_null() {
                bail!("Failed to create flexe session (check stderr for details)");
            }

            Ok(Self {
                session,
                _bin_path: bin_path,
                _elf_path: elf_path,
                _sdcard_path: sdcard_path,
                _framebuffer: framebuffer,
                #[cfg(target_os = "windows")]
                _framebuf_mutex: framebuf_mutex_box,
                _touch_state: touch_state,
            })
        }
    }

    /// Get a pointer to the CPU for the given core (0 or 1)
    pub fn cpu(&self, core: i32) -> *mut xtensa_cpu_t {
        unsafe { flexe_session_cpu(self.session, core) }
    }

    /// Run a batch of instructions on core 0
    ///
    /// Returns the number of cycles actually executed (may be less if halted)
    pub fn run_batch(&self, cycles: u32) -> i32 {
        unsafe {
            let cpu = self.cpu(0);
            if cpu.is_null() {
                return -1;
            }
            xtensa_run(cpu, cycles as i32)
        }
    }

    /// Call after each batch to sync cores and handle preemption
    pub fn post_batch(&self, batch_size: i32) {
        unsafe {
            flexe_session_post_batch(self.session, batch_size);
        }
    }

    /// Get the current PC of core 0
    pub fn pc(&self) -> u32 {
        unsafe {
            let cpu = self.cpu(0);
            if cpu.is_null() {
                tracing::warn!("pc: CPU pointer is null!");
                return 0;
            }
            let pc = (*cpu).pc;

            // Debug: Log first few PC values
            static mut FIRST_PC_CALLS: u64 = 0;
            FIRST_PC_CALLS += 1;
            if FIRST_PC_CALLS < 5 {
                tracing::info!("pc: returning 0x{:08X}", pc);
            }

            pc
        }
    }

    /// Get the total cycle count for core 0
    pub fn cycle_count(&self) -> u64 {
        unsafe {
            let cpu = self.cpu(0);
            if cpu.is_null() {
                tracing::warn!("cycle_count: CPU pointer is null!");
                return 0;
            }
            let cycle = (*cpu).cycle_count;

            // Debug: Log the raw cycle value
            static mut FIRST_CALLS: u64 = 0;
            FIRST_CALLS += 1;
            if FIRST_CALLS < 5 {
                tracing::info!("cycle_count: raw u64 value = {}", cycle);
            }

            cycle
        }
    }

    /// Get a register value from core 0 (windowed a0-a15)
    pub fn get_register(&self, reg: u32) -> u32 {
        unsafe {
            let cpu = self.cpu(0);
            if cpu.is_null() || reg >= 16 {
                return 0;
            }
            // Calculate physical register index from window
            let windowbase = (*cpu).windowbase;
            let phys_reg = ((windowbase * 4) + reg) & 63;
            (*cpu).ar[phys_reg as usize]
        }
    }

    /// Check if the CPU is halted
    pub fn is_halted(&self) -> bool {
        unsafe {
            let cpu = self.cpu(0);
            if cpu.is_null() {
                return true;
            }
            (*cpu).halted
        }
    }

    /// Get memory interface
    pub fn mem(&self) -> *mut xtensa_mem_t {
        unsafe { flexe_session_mem(self.session) }
    }

    /// Get symbol table
    pub fn symbols(&self) -> *const elf_symbols_t {
        unsafe { flexe_session_syms(self.session) }
    }

    /// Check if using native FreeRTOS
    pub fn is_native_freertos(&self) -> bool {
        unsafe {
            flexe_session_is_native_freertos(self.session) != 0
        }
    }

    /// Look up symbol name for an address
    ///
    /// Returns None if symbols are not loaded or address is not found
    /// TODO: Add elf_symbols_lookup to bindings to enable this feature
    pub fn lookup_symbol(&self, _addr: u32) -> Option<SymbolInfo> {
        // Symbol lookup not yet implemented - need to add elf_symbols_lookup to bindings
        None
    }

    /// Get all registers (a0-a15) from core 0's current window
    pub fn get_all_registers(&self) -> [u32; 16] {
        unsafe {
            let cpu = self.cpu(0);
            if cpu.is_null() {
                return [0; 16];
            }

            let windowbase = (*cpu).windowbase;
            let mut regs = [0u32; 16];
            for i in 0..16 {
                // Calculate physical register index from window
                let phys_reg = ((windowbase * 4) + i) & 63;
                regs[i as usize] = (*cpu).ar[phys_reg as usize];
            }
            regs
        }
    }

    /// Get WINDOWBASE special register
    pub fn get_windowbase(&self) -> u32 {
        unsafe {
            let cpu = self.cpu(0);
            if cpu.is_null() {
                return 0;
            }
            (*cpu).windowbase
        }
    }

    /// Get INTLEVEL from PS register
    pub fn get_intlevel(&self) -> u32 {
        unsafe {
            let cpu = self.cpu(0);
            if cpu.is_null() {
                return 0;
            }
            // INTLEVEL is bits 0-3 of PS register
            (*cpu).ps & 0xF
        }
    }
}

/// Symbol information returned by lookup
#[derive(Debug, Clone)]
pub struct SymbolInfo {
    /// Symbol name (e.g., "vTaskDelay")
    pub name: String,
    /// Symbol base address
    pub addr: u32,
    /// Symbol size in bytes
    pub size: u32,
    /// Offset from symbol base (for "name+0x123" format)
    pub offset: u32,
}

impl SymbolInfo {
    /// Format as "name+0xoffset" or just "name" if offset is 0
    pub fn format(&self) -> String {
        if self.offset == 0 {
            self.name.clone()
        } else {
            format!("{}+0x{:X}", self.name, self.offset)
        }
    }
}

impl Drop for FlexeSession {
    fn drop(&mut self) {
        unsafe {
            // Destroy pthread mutex first (before session)
            #[cfg(target_os = "windows")]
            if let Some(ref mut mutex) = self._framebuf_mutex {
                pthread_mutex_destroy(mutex.as_mut());
            }

            if !self.session.is_null() {
                flexe_session_destroy(self.session);
                self.session = ptr::null_mut();
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_session_config_default() {
        let config = SessionConfig::default();
        assert_eq!(config.bin_path, "");
        assert_eq!(config.elf_path, None);
        assert_eq!(config.sdcard_size, 0);
        assert!(!config.single_core);
    }
}
